In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('DATA.csv', error_bad_lines = False)
df.drop('stab',inplace=True, axis = 1)
df.head()

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2  8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3  0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4  3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   

         p4        g1        g2        g3        g4     stabf  
0 -1.723086  0.650456  0.859578  0.887445  0.958034  unstable  
1 -1.255012  0.413441  0.862414  0.562139  0.781760    stable  
2 -0.920492  0.163041  0.766689  0.839444  0.109853  unstable  
3 -0.997374  0.446209  0.976744  0.929381  0.362718  unstable  
4 -0.554305  0.797110  0.455450  0.656947  0.820923  unstable

In [3]:
X = df.drop('stabf', axis = 1)
y = df['stabf']

In [4]:
#split the data into training and testing sets
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size= 0.2 , random_state= 1 )

In [5]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x_train)
x_train_scale = scaler.transform(x_train)
x_test_scale = scaler.transform(x_test)

In [6]:
X_train_scale = pd.DataFrame(x_train_scale, columns = x_train.columns)
X_test_scale = pd.DataFrame(x_test_scale, columns = x_train.columns)

In [7]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(random_state = 1)
rfc.fit(X_train_scale, y_train)

RandomForestClassifier(random_state=1)

In [8]:
rfc_pred = rfc.predict(X_test_scale)

In [9]:
y_test.unique()

array(['unstable', 'stable'], dtype=object)

In [10]:
from sklearn.metrics import accuracy_score, classification_report
print (classification_report(y_test, rfc_pred, digits = 4))

              precision    recall  f1-score   support

      stable     0.9191    0.8778    0.8980       712
    unstable     0.9341    0.9573    0.9456      1288

    accuracy                         0.9290      2000
   macro avg     0.9266    0.9176    0.9218      2000
weighted avg     0.9288    0.9290    0.9286      2000



In [11]:
from sklearn.metrics import recall_score, accuracy_score, precision_score, f1_score, confusion_matrix
cm = confusion_matrix(y_test, rfc_pred, labels=["unstable","stable"])
cm

array([[1233,   55],
       [  87,  625]], dtype=int64)

In [12]:
accuracy = accuracy_score(y_test,rfc_pred)
accuracy

0.929

In [13]:
precision = precision_score(y_test,rfc_pred, pos_label= 'stable' )
print( 'Precision: {}' .format(round(precision* 100 ), 2 ))

Precision: 92


In [14]:
recall = recall_score(y_test,rfc_pred, pos_label= 'stable' )
print( 'Recall: {}' .format(round(recall* 100 ), 2 ))

Recall: 88


In [15]:
f1 = f1_score(y_test,rfc_pred, pos_label= 'stable' )
print( 'F1: {}' .format(round(f1* 100 ), 2 ))

F1: 90


In [16]:
from sklearn.ensemble import ExtraTreesClassifier
etc = ExtraTreesClassifier(random_state = 1)
etc.fit(X_train_scale,y_train)
etc_pred = etc.predict(X_test_scale)
print (classification_report(y_test,etc_pred, digits = 4))

              precision    recall  f1-score   support

      stable     0.9410    0.8511    0.8938       712
    unstable     0.9218    0.9705    0.9455      1288

    accuracy                         0.9280      2000
   macro avg     0.9314    0.9108    0.9197      2000
weighted avg     0.9287    0.9280    0.9271      2000



In [17]:
cm1 = confusion_matrix(y_test, etc_pred)
cm1

array([[ 606,  106],
       [  38, 1250]], dtype=int64)

In [18]:
accuracy1 = accuracy_score(y_test,etc_pred)
accuracy1

0.928

In [19]:
precision1 = precision_score(y_test,etc_pred, pos_label= 'stable' )
print( 'Precision1: {}' .format(round(precision1* 100 ), 2 ))

Precision1: 94


In [20]:
recall1 = recall_score(y_test,etc_pred, pos_label= 'stable' )
print( 'Recall1: {}' .format(round(recall1* 100 ), 2 ))

Recall1: 85


In [21]:
f1_1 = f1_score(y_test,etc_pred, pos_label= 'stable' )
print( 'F1_1: {}' .format(round(f1_1* 100 ), 2 ))

F1_1: 89


In [22]:
from xgboost import XGBClassifier
xgb = XGBClassifier(random_state = 1)
xgb.fit(X_train_scale, y_train)

XGBClassifier(random_state=1)

In [23]:
xgb_pred = xgb.predict(X_test_scale)

In [24]:
print (classification_report(y_test, xgb_pred, digits = 4))

              precision    recall  f1-score   support

      stable     0.9206    0.8469    0.8822       712
    unstable     0.9190    0.9596    0.9389      1288

    accuracy                         0.9195      2000
   macro avg     0.9198    0.9033    0.9105      2000
weighted avg     0.9195    0.9195    0.9187      2000



In [25]:
cm2 = confusion_matrix(y_test, xgb_pred)
cm2

array([[ 603,  109],
       [  52, 1236]], dtype=int64)

In [26]:
accuracy2 = accuracy_score(y_test,xgb_pred)
accuracy2

0.9195

In [27]:
precision2 = precision_score(y_test,xgb_pred, pos_label= 'stable' )
print( 'Precision2: {}' .format(round(precision2* 100 ), 2 ))

Precision2: 92


In [28]:
recall2 = recall_score(y_test,xgb_pred, pos_label= 'stable' )
print( 'Recall2: {}' .format(round(recall2* 100 ), 2 ))

Recall2: 85


In [29]:
f1_2 = f1_score(y_test,xgb_pred, pos_label= 'stable' )
print( 'F1_2: {}' .format(round(f1_2* 100 ), 2 ))

F1_2: 88


In [30]:
from lightgbm import LGBMClassifier
lgbm = LGBMClassifier(random_state = 1)
lgbm.fit(X_train_scale, y_train)

LGBMClassifier(random_state=1)

In [31]:
lgbm_pred = lgbm.predict(X_test_scale)
print (classification_report(y_test, lgbm_pred, digits = 4))

              precision    recall  f1-score   support

      stable     0.9297    0.8919    0.9104       712
    unstable     0.9415    0.9627    0.9520      1288

    accuracy                         0.9375      2000
   macro avg     0.9356    0.9273    0.9312      2000
weighted avg     0.9373    0.9375    0.9372      2000



In [32]:
cm3 = confusion_matrix(y_test, lgbm_pred)
cm3

array([[ 635,   77],
       [  48, 1240]], dtype=int64)

In [33]:
accuracy3 = accuracy_score(y_test,lgbm_pred)
accuracy3

0.9375

In [34]:
precision3 = precision_score(y_test,lgbm_pred, pos_label= 'stable' )
print( 'Precision3: {}' .format(round(precision3* 100 ), 2 ))

Precision3: 93


In [35]:
recall3 = recall_score(y_test,lgbm_pred, pos_label= 'stable' )
print( 'Recall3: {}' .format(round(recall3* 100 ), 2 ))

Recall3: 89


In [36]:
f1_3 = f1_score(y_test,lgbm_pred, pos_label= 'stable' )
print( 'F1_3: {}' .format(round(f1_3* 100 ), 2 ))

F1_3: 91


In [37]:
n_estimators = [50,100,300,500,1000]
min_samples_split = [2,3,5,7,9]
min_samples_leaf = [1,2,4,6,8]
max_features = ['auto','sqrt','log2',None]

In [38]:
hyperparameter_grid = {'n_estimators':n_estimators,
                      'min_samples_split':min_samples_split,
                      'min_samples_leaf':min_samples_leaf,
                      'max_features':max_features}

In [39]:
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
randommode = RandomizedSearchCV(ExtraTreesClassifier(), 
                                hyperparameter_grid, random_state = 1).fit(X_train_scale, y_train).best_estimator_

In [40]:
ETC_pred = randommode.predict(X_test_scale)

In [41]:
print (classification_report(y_test,ETC_pred))

              precision    recall  f1-score   support

      stable       0.92      0.87      0.89       712
    unstable       0.93      0.96      0.94      1288

    accuracy                           0.93      2000
   macro avg       0.93      0.91      0.92      2000
weighted avg       0.93      0.93      0.93      2000



In [44]:
RandomizedSearchCV(ExtraTreesClassifier(),hyperparameter_grid,n_iter=10,cv = 5, scoring='accuracy',n_jobs=-1,verbose=1,random_state=1).fit(X_train_scale, y_train).best_estimator_

Fitting 5 folds for each of 10 candidates, totalling 50 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  46 tasks      | elapsed:  3.3min
[Parallel(n_jobs=-1)]: Done  50 out of  50 | elapsed:  3.5min finished


ExtraTreesClassifier(max_features=None, min_samples_leaf=8, n_estimators=1000)

In [46]:
from sklearn.ensemble import ExtraTreesClassifier
etc2 = ExtraTreesClassifier(max_features=None,min_samples_split=2,min_samples_leaf=8,n_estimators=1000,random_state = 1)
etc2.fit(X_train_scale,y_train)
etc2_pred = etc2.predict(X_test_scale)
print (classification_report(y_test,etc2_pred, digits = 4))

              precision    recall  f1-score   support

      stable     0.9211    0.8694    0.8945       712
    unstable     0.9300    0.9589    0.9442      1288

    accuracy                         0.9270      2000
   macro avg     0.9256    0.9141    0.9193      2000
weighted avg     0.9268    0.9270    0.9265      2000

